model_type: yolov8n.pt
pretrained: True
seed: 0
imgsz: 640 
batch: 16 
epochs: 10
optimizer: Adam # other choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
lr0: 0.001  # learning rate 
name: 'yolov8n_exp_smalldataset' # experiment name